---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-register"
#   annotations:
#   jenkins.io/job-full-name: backstage-demo/pipeline-scm
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backstage-register-api
  description: The API template
  tags:
    - demo
    - remotefile
spec:
  type: openapi
  lifecycle: experimental
  owner: dx-team
  system: demoproject
  definition:
    $text: https://github.com/gongshishao/backstage-register/blob/main/api.yaml
