apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: template-api2
  description: The API template
  tags:
    - demo
    - remotefile
spec:
  type: openapi
  lifecycle: experimental
  owner: dx-team
  system: demoproject
  definition:
    $json: ./api.yaml
